### ISSUE TITLE
Fix needed: control for user role users not having access to all clients, because all jobs share SSH keypair

### ISSUE THREAD

**Issue by joker-x** [elkarbackup/elkarbackup#157]
Actualmente se genera un mismo certificado ssh para el usuario elkarbackup en /var/lib/elkarbackup/.ssh/id_rsa que se aplica para conectarse con cualquier cliente definido. Esto puede ser un problema serio de seguridad pues cualquier usuario puede definir un cliente y hacer backup entero de una máquina a la que no tendría porqué tener acceso.

Sería más seguro que se genera un nuevo par de claves para cada usuario definido en la web y que fuera esa clave la que se usara para conectar a sus clientes, habría que permitir también que un usuario administrador pudiera conectarse a todos los clientes definidos y no se que efectos colaterales tuviera un cambio de propietario o a la hora de ejecutar un script remotamente, pero es algo que habría que abordar en mi opinión.

**Comment by xezpeleta** [comment]
Efectivamente, los usuarios no-administradores se implementaron recientemente y hay todavía algunas funcionalidades que habría que pulir para considerarlo multiusuario de verdad.

Lo apuntamos como tarea pendiente. Gracias

**Comment by xezpeleta** [comment]
In order to use a different SSH key per user, we need to make the following changes:

- [ ] Disallow local backups to common users (otherwise it would be easy to obtain all the keys)
- [ ] Modify *GenerateKeyPairCommand*: add username as an argument. It will generate the specific keypair with a custom name (i.e. **id_rsa_username** and **id_rsa_username.pub**) in the keys directory
- [ ] Move *download/generate Public Key* option from "Manage parameters" to (user) "Preferences"
- [ ] Update Rsnapshot template, to use our custom key: `ssh -i id_rsa_username ...`

The scenario:
- Every user will have its specific keypair (if it doesn't exist the upgrade script should generate it automatically)
- As a result, common users will only be able to connect to their own clients
- Admin users will have full access to all the private keys
- Default root user will own the current keypair (**id_rsa** and **id_rsa.pub**)

Any feedback?

**Comment by elacunza** [comment]
Hi,

I think that maybe having an SSH keypair per user is not the best solution, as it would be quite odd that the keypair used depended on the owner of the job.

Maybe there should be a SSH keypair store so that:
- Each client can use a different keypair
- Each user can be permitted/denied to set a keypair in a client (keypair access), he always can use his keypairs and by default can't user other's.
- New keypairs can be created and/or uploaded to the store.

This way the solution would be more generic, and makes for example possible to use different keypairs to access different servers by clients owned by the same.

**Comment by elacunza** [comment]
We may remove "user" role and just allow creating "admin" roles for 2.0.0 too.
Also, issue can be avoided just not creating "user" rol users...

**Comment by xezpeleta** [comment]
Having a SSH keystore, different keypairs per client etc would be the best solution, but we need to do that properly as it has a security impact. That will require some time.

So I agree with @elacunza : meanwhile we should remove "user" role. Morover, I wonder if we should disable all non-admin users during the update process.

**Comment by elacunza** [comment]
I think this issue is closed by #486 , for further discussion please use #488
