### ISSUE TITLE
Upload directory changed in sudoers

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#160]
I have just upgraded a 1.2.1 installation to 1.2.2, and found the following diff for /etc/sudoers.d file:

-Cmnd_Alias ELKARBACKUP_SCRIPTS=/var/spool/elkarbackup/uploads/*
-Defaults!ELKARBACKUP_SCRIPTS env_keep += "ELKARBACKUP_LEVEL ELKARBACKUP_EVENT ELKARBACKUP_URL ELKARBACKUP_ID ELKARBACKUP_PATH ELKARBACKUP_STATUS ELKARBACKUP_CLIENT_NAME ELKARBACKUP_JOB_NAME ELKARBACKUP_OWNER_EMAIL ELKARBACKUP_RECIPIENT_LIST ELKARBACKUP_CLIENT_TOTAL_SIZE ELKARBACKUP_JOB_TOTAL_SIZE ELKARBACKUP_JOB_RUN_SIZE ELKARBACKUP_CLIENT_STARTTIME ELKARBACKUP_CLIENT_ENDTIME ELKARBACKUP_JOB_STARTTIME ELKARBACKUP_JOB_ENDTIME"
+Cmnd_Alias ELKARBACKUP_SCRIPTS=/usr/share/elkarbackup/uploaded/*
+Defaults!ELKARBACKUP_SCRIPTS env_keep += "ELKARBACKUP_LEVEL ELKARBACKUP_EVENT ELKARBACKUP_URL ELKARBACKUP_ID ELKARBACKUP_PATH ELKARBACKUP_STATUS ELKARBACKUP_CLIENT_NAME ELKARBACKUP_JOB_NAME ELKARBACKUP_OWNER_EMAIL ELKARBACKUP_RECIPIENT_LIST ELKARBACKUP_CLIENT_TOTAL_SIZE ELKARBACKUP_JOB_TOTAL_SIZE ELKARBACKUP_JOB_RUN_SIZE ELKARBACKUP_CLIENT_STARTTIME ELKARBACKUP_CLIENT_ENDTIME ELKARBACKUP_JOB_STARTTIME ELKARBACKUP_JOB_ENDTIME ELKARBACKUP_SSH_ARGS"

Notice that ELKARBACKUP_SCRIPTS directory has changed, but after the upgrade "uploaded" does not exist, and "uploads" does exist. I think this is a bug and should be fixed back to the old value?

Cheers

**Comment by xezpeleta** [comment]
Thanks you @elacunza 

Same here. Script execution failed after upgrading to 1.2.2

Apparently the bug is caused by the deb installation package. Default [sudoers template](https://github.com/elkarbackup/elkarbackup/blob/master/debian/etc/sudoers.d/elkarbackup#L1) value always has been `/usr/share/elkarbackup/uploaded` (don't remember why) but during the first installation the [postinst script](https://github.com/elkarbackup/elkarbackup/blob/master/debian/DEBIAN/postinst#L136) changes that default value from `/usr/share/elkarbackup/uploaded` to `/var/spool/elkarbackup/uploads`

The problem is that it only changes it in the installation step, not in the configure step. So in v1.2.2 the tknika sudoers template [has been updated](https://github.com/elkarbackup/elkarbackup/pull/155) with a new environment variable and the ELKARBACKUP_SCRIPTS has been _restored_ to its default value.

I will fix it changing the postinst script, adding some code to modify ELKARBACKUP_SCRIPTS in the sudoers template every `postinst configure`, taking the value from users _upload_dir_ (parameters.yml).

**Comment by elacunza** [comment]
It's strange, I have it correctly set to /var/spool/elkarbackup/uploads/* ... didn't think there could be a postscript changing the value.

I don't know why you're seeing the issue after the update?

I have it right in three different servers... :-)

**Comment by xezpeleta** [comment]
Ok, forget what I said!!!

It was my fault: during the installation I said "no" to change the sudoers file and after that, I changed it by myself (by hand, with a `mv`). That's why I was seeing the old directory "uploaded" in my file...

To check that everything was working well, I did an `apt-get install --reinstall elkarbackup` and, yes, the installer replaced my ELKARBACKP_SCRIPTS with the one in parameters.yml :)

Anyway, I guess it's better if we change the sudoers template with the new default directory (`/var/spool/elkarbackup/uploads/*`);
