### ISSUE TITLE
english user guide missing

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#182]
Hello

I am missing an english installation guide. I am trying to learn with Google translator but most of the time it makes no sense. I have no idea how to use your solution in the right manner.

Is there an estimation when a english user guide will be available?
What do I need to configure on the client that it accepts the incoming request from the backup server?
Will ElkarBackup running with nginx?
What is the "Repository backups script" for?

Kind regards
nephilim

**Comment by parreitu** [comment]
Hello,

1- The English user guide will be finished after Christmas.
2- The client: nowadays depending on the client's system you need to do
different things
 2.1 - If the client is a GNU/Linux machine, you need to install
openssh-server and rsync and configure the Elkarbackup's public key in the
GNU/Linux client (
https://docs.elkarbackup.org/es/clientes_y_tareas/anadiendo_clientes_gnulinux.html).

 2.2 - If the client is a Windows machine, you need a rsync server there.
In this moment we are using (
https://docs.elkarbackup.org/es/clientes_y_tareas/anadiendo_clientes_windows.html
)

3.- Repository backups script: As you know one of the master keys for a
backup is to have copies of your backups in a different place. This script
is a way to help you in order to set up an automated replication or
synchronization of the whole backup folder (all the clientes and all the
tasks) in another machine.

See you




2016-12-13 5:53 GMT+01:00 nephilim75 <notifications@github.com>:

**Comment by nephilim75** [comment]
Hej

thank you so much. Looking forward to the next steps. 

1, If I try to copy the public key to client, the system returns `/usr/bin/ssh-copy-id: ERROR: failed to open ID file './Publickey': No such file`

2. I cannot see a generate button in section "manage parameters" as it is shown in https://docs.elkarbackup.org/es/clientes_y_tareas/anadiendo_clientes_gnulinux.html. Am I doing something wrong?

3. In the same section it looks like the passwords for database and mail setup got lost (empty fields). Is this part of the design or a bug?

Kind regards
//neph

**Comment by parreitu** [comment]
Do you see the "Download" option ?

[image: Txertatutako irudia 3]


Another option is to copy the public key using a terminal in the
Elkarbackup server. Suppose that your client IP address is 10.15.181.155

root@elkarbackup:~# ssh-copy-id -i /var/lib/elkarbackup/.ssh/id_rsa.pub
root@10.15.181.155

"In the same section it looks like the passwords for database and mail
setup got lost (empty fields). Is this part of the design or a bug?"  -->
It is part of the design





2016-12-13 17:33 GMT+01:00 nephilim75 <notifications@github.com>:

**Comment by nephilim75** [comment]
Hej

I do not see the image but I can see the option to  download the public key.

I added the key to authorized_keys file on the server I want to take the backup from. But I still cannot login to that server without be prompted for a password.

This is the config of my sshd_config on the server I want to take the backup from:
```
# Package generated configuration file
# See the sshd_config(5) manpage for details

# What ports, IPs and protocols we listen for
Port 22
# Use these options to restrict which interfaces/protocols sshd will bind to
#ListenAddress ::
#ListenAddress 0.0.0.0
Protocol 2
# HostKeys for protocol version 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
#Privilege Separation is turned on for security
UsePrivilegeSeparation yes

# Lifetime and size of ephemeral version 1 server key
KeyRegenerationInterval 3600
ServerKeyBits 1024

# Logging
SyslogFacility AUTH
LogLevel INFO

# Authentication:
LoginGraceTime 120
PermitRootLogin without-password
StrictModes yes

RSAAuthentication yes
PubkeyAuthentication yes
AuthorizedKeysFile      %h/.ssh/authorized_keys

# Don't read the user's ~/.rhosts and ~/.shosts files
IgnoreRhosts yes
# For this to work you will also need host keys in /etc/ssh_known_hosts
RhostsRSAAuthentication no
# similar for protocol version 2
HostbasedAuthentication no
# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
#IgnoreUserKnownHosts yes

# To enable empty passwords, change to yes (NOT RECOMMENDED)
PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues with
# some PAM modules and threads)
ChallengeResponseAuthentication no

# Change to no to disable tunnelled clear text passwords
#PasswordAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosGetAFSToken no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
```

I am not sure what I am making wrong. Any hint for me?

Kind regards
//nephilim

**Comment by xezpeleta** [comment]
Hi @nephilim75 

Can you try this please?

```bash
# From your ElkarBackup server:
$ su elkarbackup
$ ssh root@your-linux-computer
```

Does it work? What output do you get?

Thanks

**Comment by nephilim75** [comment]
Hello Xabi

what is the password that will be required for `su elkarbackup`? Is it the root password from the installation of the server?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 it didn't require any password in my server.

What distribution are you using in the server? Aren't you as root?

**Comment by nephilim75** [comment]
Hej Xabi

thank you so much. This worked fine. I wasn't logged in as root. Once I was using elkarbackup user afterwards I was able to establish the connection to the client. But why do I can't use the root user to connect to the client? Why is it working with elkarbackup user only?

Kind regards
//neph

**Comment by antton** [comment]
The ssh key is generated for elkarbackup user, that's why root can't logged in with this key.

But us root you con always use the -i parameter with the elkarbackup key to login on your remote servers from this machine.

I hope you get it all right now ;)

Antton

**Comment by nephilim75** [comment]
Hello Antton

> But us root you con always use the -i parameter with the elkarbackup key to login on your remote servers from this machine.

Unfortuanetly I don't know what this means and in which context. Could you please provide an example?

Thank you so much.

Kind regards
//neph

**Comment by xezpeleta** [comment]
> Once I was using elkarbackup user afterwards I was able to establish the connection to the client. But why do I can't use the root user to connect to the client? Why is it working with elkarbackup user only?

@nephilim75 actually you can do that as "root" user indicating the pubkey path, as Antton said, but depending on the Linux distribution you use, you can have problems doing that because the file permissions:

```sh
$ ssh -i /var/lib/elkarbackup/.ssh/id_rsa.pub root@you-linux-machine
```

Anyway, if the command in https://github.com/elkarbackup/elkarbackup/issues/182#issuecomment-267573745 worked for you, that means that both, your Elkarbackup server and your Linux machine are correctly configured.

Now you can check if everything works well, trying to "Run now" your job from the web interface. Please, be sure that your client URL contains also the username, i.e. `root@your-linux-machine`

**Comment by nephilim75** [comment]
Thank you so much for your efforts and support. :-)

> Now you can check if everything works well, trying to "Run now" your job from the web interface.

It does! :-)
