### ISSUE TITLE
Feature: german translation

### ISSUE THREAD

**Issue by nephilim75** [elkarbackup/elkarbackup#185]
Hello

is it planned to have a german language package and documentation? I would like to contribute and I would like to offer the translation part.

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

Sure! we'd love to have the german translation! Recently another german user offered us to contribute:

https://groups.google.com/forum/#!topic/elkarbackup-users/s8Rkz3H-0MQ

But actually we don't have more news about that. If you're interested to contribute, here you have the instructions to follow:

1. The file to be translated is [BinovoElkarBackup.en.yml](https://raw.githubusercontent.com/elkarbackup/elkarbackup/master/src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.en.yml)
2. You can clone the project, create the new translated file `BinovoElkarBackup.de.yml` under the same translations directory, and finally send us a [Pull Request](https://github.com/elkarbackup/elkarbackup/pulls)
3. If you are not familiar to GitHub workflow, don't worry, you can simply send us that file using this issue

Regarding the documentation, @parreitu is currently working on the english translation. It will be ready sooner rather than later. We'll be glad to have your contribution too!

Thank you very much

**Comment by nephilim75** [comment]
Hi Xabi,

I started to translate the language pack. Let me know when the translation of documantation can start.

2 questions left.

1. What do I need to do to implement the language pack into my system. I want to check my results by my own without publishing them until it is done completely.
2. Is there an overview what text is shown on which page. It happens that the context is helpful for a useful translation.

Thank you in advance
//neph

**Comment by xezpeleta** [comment]
> What do I need to do to implement the language pack into my system. I want to check my results by my own without publishing them until it is done completely.

The easiest way could be to change an existing translation (for instance, the english one). Then you have to clean the cache and dump assets:

```
/usr/share/elkarbackup/app/console cache:clear --env=prod
/usr/share/elkarbackup/app/console assetic:dump --env=production
```

Once you do that, you'll see your own translated strings.

> Is there an overview what text is shown on which page. It happens that the context is helpful for a useful translation.

No, sorry.

**Comment by nephilim75** [comment]
Thank you so much. It works as mentioned.

Where can I send messages to to discuss some translation related stuff. Shall this be discussed here or somewhere else? There are some questions left where it is not clear to me what they are meaning. Before I use something stupid I need some assistance.

I have found some strings which are not listed in the language.yml file but shown on an EB page. Example is the policy area. If you edit the default policy you usually can edit the time and date the application takes the snapshots. In weekly area will shown english text but not the translated one.

![example](https://cloud.githubusercontent.com/assets/19992865/21402688/fd9021e6-c7b9-11e6-99ce-8db5a2835b6f.png)

Status of application translation: more than 85% done.

Kind regards
//neph

**Comment by xezpeleta** [comment]
> Status of application translation: more than 85% done.

Wow! Good job! :D

> I have found some strings which are not listed in the language.yml

You're right. Anyway, even if they aren't in the english yml the strings are prepared to be translated (I guess), so you can add them to your file:

```yml
'Day of week': 'translated string'
'Number of copies to keep': 'translated string'
```

Thanks you

**Comment by nephilim75** [comment]
`'Number of copies to keep': 'translated string'` is already in the file. For "during the day" tab it is ok as you can see beneath.

![dd](https://cloud.githubusercontent.com/assets/19992865/21416448/52efa220-c813-11e6-9cfa-d67686e457d8.PNG)

But not for "daily, weekly, monthly and yearly" tab:

![policies](https://cloud.githubusercontent.com/assets/19992865/21416479/88cb32d8-c813-11e6-8760-42bacb459792.PNG)

Looks like the translation isn't being fetched. Any hint for me to get it fixed as well?

Kind regards
//neph

**Comment by xezpeleta** [comment]
Ok, I've already fixed that. Will be solved in the next version.

**Comment by nephilim75** [comment]
Hej Xabi,

I need your assistance, again. There are 9 strings left where I don't got the meaning of them yet. Would you please help me to understand the meaning of them?

- The application invoques the script using the user for backups.

- (empty in client)

- Can not have the retention count of the first backup level set to 1, and have a second backup level

- du begin
('Client "%clientid%", Job "%jobid%" du begin.': 'Gerät "%clientid%", Aufgabe "%jobid%" du begin.')

- du end
('Client "%clientid%", Job "%jobid%" du end.': 'Gerät "%clientid%", Aufgabe "%jobid%" du end.')

- Error unlinking config file %filename%.

- Error closing config file %filename%.

- Error log for backup from job %joburl%

- Policy %policyid% has no active retains

Thank you in advance

Kind regards
//neph

**Comment by xezpeleta** [comment]
>  The application invokes the script using the user for backups.

Context: scripts (help message).

It means that the script will be executed as the same user configured under client SSH URL (my-user@my-host)

 > (empty in client)

Context: scripts (help message), environment variables.

This envar will be empty when the script is running as pre/post client script.

> Can not have the retention count of the first backup level set to 1, and have a second backup level

Context: policies, warning message

I haven't found another better way to explain it. It's a warning text. The policy designer form will show you this message when you choose 1 for the first backup retention level and you have a second backup level. You should increase that retention level, or remove the second backup level.

> du begin
> ('Client "%clientid%", Job "%jobid%" du begin.': 'Gerät "%clientid%", Aufgabe "%jobid%" du begin.')
> du end
> ('Client "%clientid%", Job "%jobid%" du end.': 'Gerät "%clientid%", Aufgabe "%jobid%" du end.')

Context: logs
Don't worry, you can keep these messages as they were (in english).

> Error unlinking config file %filename%.
> Error closing config file %filename%.
> Error log for backup from job %joburl%
> Policy %policyid% has no active retains

Context: logs (error messages)
Same as above. I suggest you not to translate these messages. Can be useful to keep them in english to debug purposes.

Thanks

**Comment by nephilim75** [comment]
Hello Xabi

would you please assist me to get the following more clear?

> Even hourly calls only rotate the directories, without even connecting to the client. This ensures that the snapshots are consistent with the cost of an additional snapshot used only for syncing. 

Thank you so much

Kind regards
//neph

**Comment by parreitu** [comment]
Hello

Thease days I'm working in the English documentation for the last
Elkarbackup version. It isn't finished, but perhaps the English
documentation could help you to understand better the logic of rsnapshot
(and consecuently Elkarbackup) rotation logic.

Here you have the fork I did to work in the new version:

https://github.com/parreitu/elkarbackup-docs/blob/master/en/SUMMARY.md

Put special attention to "Policies" and "A review of concepts: RSnapshot"
sections

kind regards




2016-12-30 13:28 GMT+01:00 nephilim75 <notifications@github.com>:

**Comment by xezpeleta** [comment]
@nephilim75 You have it explained much better here:

> __I run rsnapshot for the first time, but nothing happens. Why?___
>
>rsnapshot does two major things - actual backup (with rsync) and rotation (moving snapshots around). Before it can do rotations, it needs to have at least one actual backup. So you need to understand which rsnapshot invocation will make an actual backup.
>
>For example, if you have sync_first enabled, then you need to run rsnapshot sync (which makes a backup) before you can do a rotation like rsnapshot hourly or rsnapshot daily. With sync_first enabled, all intervals (hourly, daily, etc) just do rotation.
>
>If you do not have sync_first (it is disabled by default), then the backup is made by the lowest interval (that is, the first one that you listed in your rsnapshot.conf). The other (higher) intervals do rotation. For example, if you have intervals hourly, daily, weekly and monthly, then you need to run rsnapshot hourly to do a backup before the other intervals (daily, weekly and monthly which do rotations) will do anything.
>
>In fact, you need a complete set of hourly backups before a rsnapshot daily will do anything. Similarly, you need a complete set of daily backups (usually 7) before rsnapshot weekly will do anything.

http://rsnapshot.org/faq.html

**Comment by parreitu** [comment]
Hi !!
I've finished the English version of the documentation. I'd be grateful if
you could review it and report mistakes.

https://docs.elkarbackup.org/en/

Also if you think that something important is missing, you can put it as a
comment in this issue

https://github.com/elkarbackup/elkarbackup-docs/issues/3

Thanks and happy new year!!


- - - - - - - - - - - - - - - - - - - - - - - - - - - -
Zuk nahi badezu, hemendik aurrera euskaraz egingo degu

Pedro Arreitunandia

El 21 dic. 2016 7:07, "nephilim75" <notifications@github.com> escribió:

Hi Xabi,

I started to translate the language pack. Let me know when the translation
of documantation can start.

2 questions left.

   1. What do I need to do to implement the language pack into my system. I
   want to check my results by my own without publishing them until it is done
   completely.
   2. Is there an overview what text is shown on which page. It happens
   that the context is helpful for a useful translation.

Thank you in advance
//neph

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elkarbackup/elkarbackup/issues/185#issuecomment-268444146>,
or mute the thread

**Comment by nephilim75** [comment]
Hej guys

happy new year to all of you.

I am testing right now and I believe I am almost finished. But there is just one thing left.

Sorry to bother you again. Please help me to get this warning message more clear:

`Can not have the retention count of the first backup level set to 1, and have a second backup level`

When does it coming up? Where does it coming up in application? What do I need to do to create an issue that brings that message up?

Once I got language pack finished I will start to translate the documentation.

Kind regards
//neph

**Comment by xezpeleta** [comment]
Hi @nephilim75 

I'm glad your translation is almost finished.

_'Can not have the retention count of the first backup level set to 1, and have a second backup level'_

That's the Rsnapshot behavior:
http://www.backupcentral.com/forum/18/226280

The message will be shown when you have a policy where the first backup level (i.e. hourly) has a retention level to 1, and you want to set up a second backup level (i.e. daily).

Due to the Rsnapshot rotation behavior, if you want to add a *daily* backup level, you need to increase the retention under *hourly* (i.e. from 1 to 2). 

Anyway, do not worry. It's not necessary to translate all the strings. I consider a partial translation it's better than nothing. So, if you want you can send us your translation file as it is.

Thanks again

**Comment by parreitu** [comment]
Hi @nephilim75 <https://github.com/nephilim75>

Have you read this ?    https://docs.elkarbackup.org/en/rotation.html



2017-01-11 20:46 GMT+01:00 Xabi <notifications@github.com>:

**Comment by nephilim75** [comment]
Hello

it's done. Find the file attached.

Kind regards
//neph
[BinovoElkarBackup.de.yml.zip](https://github.com/elkarbackup/elkarbackup/files/702519/BinovoElkarBackup.de.yml.zip)

**Comment by xezpeleta** [comment]
Great!! Thanks. I'm going to add it and release a new version. I'll keep you updated.

**Comment by xezpeleta** [comment]
Hi @nephilim75 

I've just created a new version with your contribution: https://github.com/elkarbackup/elkarbackup/releases/tag/v1.2.5

I will upload it to the debian/ubuntu repo during the next days

Thanks again

**Comment by xezpeleta** [comment]
@nephilim75 I've just uploaded the new release to the Ubuntu/Debian repo.

You can upgrade to the new version now using `apt-get update && apt-get upgrade`

**Comment by nephilim75** [comment]
This was working perfectly fine. Thank you so much for all your efforts.

I found more minor translation issues. I will send a pull request once I have reviewed everything. ;-)

Kind regards
//neph
