### ISSUE TITLE
Maximum backup size reported is 2048G

### ISSUE THREAD

**Issue by gvdijnsen** [elkarbackup/elkarbackup#217]
We have several backups that are much larger than 2TB, but the maximum reported is 2TB. This is probably related to the system du command result being forced into an integer in src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php on line 467.

**Comment by xezpeleta** [comment]
Thanks @gvdijnsen , can you attach a screenshot?

**Comment by gvdijnsen** [comment]
![backup_example](https://cloud.githubusercontent.com/assets/470608/26106868/ab2cbc1a-3a47-11e7-8284-0e02d81bc86a.png)

**Comment by xezpeleta** [comment]
Thanks @gvdijnsen 

I'd say that the problem is that the value is stored/returned as _integer_ (in KB) :S

- [Jobs](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Entity/Job.php#L110)
- [Clients](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Entity/Client.php#L296)

The maximum value for the signed integer type is 2147483647 (2047,99GB)
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#integer

We have to change the property from _integer_ to _bigint_. We also should modify the template [clients.html.twig](https://github.com/elkarbackup/elkarbackup/blob/master/src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig) to show the disk usage in TBs when the value is > 1024GB.

I will try to fix it for the upcoming version. I'll keep you updated.

Thanks

**Comment by xezpeleta** [comment]
Hi @gvdijnsen ,

I've just fixed this bug.
The upcoming version v1.2.6 will be able to report the correct backup size:

![captura de pantalla 2017-06-27 a las 19 34 47](https://user-images.githubusercontent.com/1846038/27602188-315f3718-5b72-11e7-8217-4d58622d9b0d.png)

Thanks for your help.
