### ISSUE TITLE
Log-Path

### ISSUE THREAD

**Issue by ich92** [elkarbackup/elkarbackup#313]
The path for the log files to download from logged errors is wrong:
my elkarurl: https://hostname/elkarbackup
url for log file: https://hostname/log/1878/download
correct one: https://hostname/elkarbackup/log/1878/download

**Comment by xezpeleta** [comment]
Hi @ich92 

Please, can you confirm that you have your "**_Url prefix_**" setting correctly configured (Manage parameters)?

Thanks

**Comment by ich92** [comment]
Hi @xezpeleta 
Thanks for pointing me on that parameter. It was not set.
But even after setting the parameter and reboot my whole system the path to the logfile is wrong.
Everything else works as expected and seems to be correct.

**Comment by elacunza** [comment]
I have seen this issue multiple times. Will try to reproduce and report the findings.

**Comment by elacunza** [comment]
I have seen where the problem is.
To reproduce, 
1. Go to preferences, so that a log entry is generated
2. Change elkarbackup directory in apache, from / to for example /elkarbackup
3. In parameters.yml, set "url_prefix" accordingly; for the previous example: /elkarbackup
4. Go to preferences, so that a log entry is generated (a second one)
5. Go to logs

We can see that the link for each of the visits to preferences is different. The second one will work now, but not the first. Seems we should save the link unprefixed, and prefix it just in the view. This isn't very important, as the prefix is set on installation and not changed anymore after that.

But also as reported by @ich92 , the link generated for downloading the logfile is not using the "url_prefix" parameter:
https://github.com/elkarbackup/elkarbackup/blob/3f4f8c5950f120d55c679a4a92f54cea5552e533/src/Binovo/ElkarBackupBundle/Resources/views/Default/logs.html.twig#L41

We should fix that because that breaks all non-/ prefixes.
