### ISSUE TITLE
Remove Tahoe support

### ISSUE THREAD

**Issue by elacunza** [elkarbackup/elkarbackup#458]
As commented in #457 , remove Tahoe support and release 1.4.0rc2 as 2.0.0

**Comment by igorbga** [comment]
@uanabitarte is working on removing it during the upgrade to Symfony 4.4.

The removal of Tahoe and the change to Symfony 4.4 shouldn't take too long, 1 or 2 weeks at most.

The jump to 3.4 was useful for @uanabitarte in order to make the changes in a more progressive way but does not by itself give any advantage to end users over the use of Symfony 4.4. 

So if nothing is to be objected we will release it all togheter as 2.0.0rc1.
