### ISSUE TITLE
Use ACLS to give permission for the elkarbackup webuser

### ISSUE THREAD

**Issue by JoshuaPettus** [elkarbackup/elkarbackup#527]
When storing backups there is a choice between being able to access the data through the web interface or keeping the original permissions of the file.

I very well maybe missing something and totally a bad idea, but what if you retained the original permissions of the file from the host, and gave the elkarbackup user access to the file by setting a linux acl?  Then remove that ACL permission when the file is recovered?
Wouldn't that allow people to have their cake and eat it?

**Comment by antton** [comment]
Hi!

I did it a few years ago and you can find it on pre/post scripts repository.
Using the getacl command first to keep the original permissions of the
files and then you can restore them again when you need it.

https://github.com/elkarbackup/elkarbackup-scripts/tree/master/backup-permissions

I think you are talking about the same problem ;)

We can improve it or even talk about if it would be necessary integrate
something similar on the core.

Take care!

**Comment by JoshuaPettus** [comment]
I'm a little confused, I thought the checkbox "Use local permissions" was used to retain the original permissions of the source file. And therefore permissions would be further retained when they are restored?
What's the benefit of backing the permissions up to a file?

I'm talking about keeping the existing source permissions as in "Use local permission" but then tacking on read access for the elkarbackup user via acl.  The point being that read access for the elkarbackup user is a requirement for the web server to see list backup files via the web interface.

A script is not a bad idea for this first part, and could certainly give that a try. 

But the second part, of removing the acl in the backup before restoring it to the machine, thereby leaving the file with the same permission it had when it was backed up.  As far as I can see, that part would have to be baked into core as scripts aren't invoked for this job.

**Comment by antton** [comment]
Hi Joshua,

That second part was developed at the time but was not included at the end
in the core, you have a PR in github with it, anyway and I repeat again
that if it is necessary, we could revisit this issue now, that the new
version of Elkarbackup is being developed.

Let's add @elakunza @xezpeleta @parreitu @uanabitarte and @igorbga into the
conversation ;)

Bye

**Comment by igorbga** [comment]
Antton I guess you meant @elacunza .

**Comment by antton** [comment]
You are right, sorry for my typo mistake!

**Comment by igorbga** [comment]
I don't know much about this feature of Elkarbackup so take my comment with a grain of salt. What Joshua proposes sounds reasonable although maybe not so "safe" or "trivial" to implement right.

When using many hosts you might or might not have your user UIDs and groups centralized or aligned and shared among all of them. For example UID 33 is "www-data" user in my Ubuntu but seems to be "amanda" user in Redhat. That's probably even worse for people's user.

When you preserve "local permissions" you are risking to unintentionally give permissions in your Elkarbackup server to do all kind of nasty things through the use of your backup files. But obviously that's not due to Joshua's proposed addition, that's a risk that you already take in the same moment that you "Use local permissions". Probably this is something that you can live with, after all Elkarbackup server is probably only shell accesible by admins. If you are sharing Elkarbackup server for other purposes you should probably stay away from "Use local permissions".

But the point is that in your Elkarbackup server you might have user "elkarbackup" with whatever Uid it uses and this uid might have another meaning in other hosts. So probably is not always evident if you should or should not add/remove the additional ACL. Yes, that's a corner case, but one that could happen.


What about this: https://bindfs.org/

It seems that bindfs can be used to "remount" a file system with "different permissions". Maybe we could just use it to allow "elkarbackup" to access all backup files in read mode no matter what the permissions are.

**Comment by elacunza** [comment]
We are tracking this on #201 . It isn't in our roadmap but will gladly review PRs.
The short answer is that keeping remote permissions in the local elkarbackup server is not evident, as user/groups may be different. Please read #201 for the full info.
