### ISSUE TITLE
Parameters form not showing the updated values

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#538]
### Describe the bug

- Elkarbackup version: v2.0.1, master
- OS: Debian 10 Buster

### Steps to reproduce the behavior

1. Go to the **_Parameters_** section
2. Change a random value: _**i.e. "Max parallel jobs"**_ from 1 to 3
3. Click "Save"

### Expected vs actual behavior

We should see the updated value (3) for "Max parallel jobs"
We see the old value (1), even if the parameters.yaml has been changed correctly.

Workaround: after running a `bin/console cache:clear` the form shows the correct information

**Comment by larsfessler** [comment]
I have the same issue on Ubuntu 20.4. I newly installed Elkarbackup as described here:
https://docs.elkarbackup.org/docs/installation.html
Everytime i save new values on the manage parameters page it shows the old values again. I changed the mailer parameters.

The workaround from xezpeleta works. But you have to do it for every single change in the parameters.

Additionally it creates some insecure feeling with me about changes of values in other parts of the application. It makes me feel unsure if there might be other adjustments jobs, policies,... which might not be consistently refreshed, since they also seem to be cached. I am just evaluating Elkarbackup for near future use. So i have not tested everything yet.

**Just to complete the description - not a clue if it could have anything to do with the issue:** 
During the installation **sudo apt install elkarbackup** brougt up an error about a missing dependency. So i installed the following manually:
**sudo apt install default-mysql-client**
After that i did the following again:
**sudo apt install elkarbackup**

**Comment by elacunza** [comment]
Hi @larsfessler , this issue should be limited to "manage parameters" screen. Those parameters are in a system file instead of the database, and it seems something broke when developing 2.0.x

**Comment by larsfessler** [comment]
Thank you very much again for the quick response. It eases my concerns quite a lot.

**Comment by elacunza** [comment]
I spent a couple of hours looking at this. It doesn't work at all, doesn't seem a permission issue either.
Works OK in 1.3.5 , so it's related to Symfony upgrades.
clearCache() implementation in DefaultController is totally revamped; new one doesn't work. Has to be tested with prod environment, as debug recreates cache for each page load.

**Comment by xezpeleta** [comment]
Hi @elacunza 

Can we fix it replacing the current clearCache() with `console cache:clear` command execution?

```php
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

protected function clearCache()
    {
        $process = new Process(['php', 'bin/console', 'cache:clear']);
        $process->run();
        ...
    }
```

**Comment by igorbga** [comment]
@xezpeleta to be honest I don't like your proposal and I was hoping for at least something like this: https://symfony.com/doc/4.4/console/command_in_controller.html

But I thought, no way, sure that it we check the implemenation for CacheClearCommand we can find an easy service injected that we can just also inject and use, something in the style of what we already do with the cacheClearer.

But then I saw the implementation: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php

And my mind blow... clearing the cache is not such an obvius thing, does not seem to be easily encapsulated in a service and it might have some implications when done while running the app itseld. So we'd better call it as a external process as you suggest.

So my last concern about your code is about the workdir. Are we guaranted to be in the proper directory when calling clearCache ?

Maybe we should inject the project dir and build an absoulte path for the console.

The same concern rises about 'php'. I don't think is safe enough to assume that php will be availabe in the PAT. Maybe this helps: https://stackoverflow.com/questions/3889486/how-can-i-get-the-path-of-the-php-binary-from-php

**Comment by igorbga** [comment]
Seems like getting the absolute path for PHP binary will be troublesome. PHP in Apache might be running in FastCGI mode or as a module and then it might know nothing about the PHP binary.
Maybe we will have to assume that "php" is in the path and add an optional parameter to specify the absolute path to the binary :(

**Comment by elacunza** [comment]
So then, shall be try the intermediate way?  https://symfony.com/doc/4.4/console/command_in_controller.html

Seems the most reasonable way...

**Comment by igorbga** [comment]
Our TickCommand does already execute SymfonyCommands, so I gave it a look:
https://github.com/elkarbackup/elkarbackup/blob/b1587b6d0b38d59673203390da1960de127feee9/src/Command/TickCommand.php#L243

**Comment by elacunza** [comment]
Pending merge to master
