### ISSUE TITLE
hautelook/AliceBundle is gone (required by SymfonyFramework)

### ISSUE THREAD

**Issue by xezpeleta** [elkarbackup/elkarbackup#600]
### Describe the bug

CI tests failed with the following error during ElkarBackup installation:

```
Downloading twig/extra-bundle (v3.3.0)
Failed to download hautelook/alice-bundle from dist: The "https://api.github.com/repos/hautelook/AliceBundle/zipball/17c5199b2a6efbc1383b0afe1cddfa3c176b7b6f" file could not be downloaded (HTTP/2 404 )
```

![image](https://user-images.githubusercontent.com/1846038/132850206-55c1a421-0a2f-4107-87fb-f3115a3c8cd5.png)

More info about this problem:
- https://twitter.com/tfidry/status/1436090358950150145
- https://github.com/nelmio/alice/issues/1089

**Comment by hopeseekr** [comment]
So I run the Bettergist Collective which usually archives every single PHP package at least 2x a year. I didn't archive in 2021 because I'm working so much and there never seems to be much [psychological] support in the PHP community, but I do have a backup of this package from May 2020.

I have created a packagist package and everything. Latest version archived: v2.7.2.

https://github.com/bettergistco/hautelook.alice-bundle
https://packagist.org/packages/bettergist/hautelook-alice-bundle

    composer require bettergist/hautelook-alice-bundle

The entire 100 GB torrent of all PHP packagist packages as of December 2020 is floating around right here: https://github.com/bettergistco/PackagistArchive
